# Generated by Django 3.2 on 2021-04-20 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('profile_picture', models.ImageField(default='', upload_to='merchant_images/')),
                ('description', models.TextField()),
                ('store_name', models.CharField(max_length=20)),
                ('phone_number', models.CharField(max_length=15)),
                ('rating', models.IntegerField(default=0)),
            ],
        ),
    ]
